config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :locations do
    resources :appointments, only: [:index, :show, :new]
  end
  resources :clients do
    resources :appointments, only: [:index, :show, :new]
  end
  get 'welcome/home'
  root 'welcome#home'

  get '/about', to: 'welcome#about'

  get '/locations/:id/client_list', to: 'locations#client_list', as: 'client_list'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :appointments, dependent: :destroy
  has_many :templates, through: :appointments

  def value
    appointments.collect { |a| a.price }.compact.inject(0, :+)
  end

  def appointment_count
    @appointment_count ||= appointments.count
  end

  ## Validations

  validates :name, presence: true
  validates :email, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i, message: 'Please enter a valid email address' }, allow_blank: true
  validates :phone_number, format: { with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "Please enter a valid phone number (123) 456-7890" }, allow_blank: true

  include ActiveModel::Validations

  class UserIdValidator < ActiveModel::Validator
    def validate(record)
      if User.find_by(id: record.user_id)
        record.errors.delete :user_id
      end
      if record.user_id && User.find_by(id: record.user_id).nil?
        record.errors[:user_id] << "User not found."
      end
    end
  end

  validates_with UserIdValidator

  ##

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = []
    @clients = current_user.clients if current_user
  end

  def show
    @appointments = @client.appointments
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.valid?
      @client.save
      redirect_to clients_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @client.update(client_params)
    redirect_to client_path(@client)
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private

  def set_client
    @client = Client.find_by(id: params[:id])
    if @client.nil?
      flash[:error] = "Client not found."
      redirect_to clients_path
    end
  end

  def client_params
    params.require(:client).permit(:name, :email, :phone_number)
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
  def client_email(client)
    client.email if client.email != ""
  end
  
  def client_phone(client)
    if client.phone_number && client.phone_number != ""
      number_array = client.phone_number.gsub(/\D/, '').split(//)  
      "(#{number_array[0,3].join}) #{number_array[3,3].join}-#{number_array[6,4].join}"
    end
  end
  
  def client_name(client)
    if current_page?(clients_path)
      link_to client.name, client_path(client)
    else
      client.name
    end
  end
  
  def client_value(client)
    number_to_currency(client.value) if client.value != 0
  end
  
  def appointment_count(client)
    link_to "Total Appointments: #{client.appointment_count}", client_path(client)
  end
  
end

app/views/clients/_client.html.erb
<div class="client">
  <p class="name"><%= client_name(client) %></p>
  <p><%= client_email(client) %></p>
  <p><%= client_phone(client) %></p>
  <p><%= pluralize(client.appointment_count, "appointment") %></p>
  <p>Value: <%= client_value(client) %></p>
      <p><%= link_to "Edit", edit_client_path(client), class: "btn btn-secondary" %> <%= link_to "Delete", client, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this client?" } %>   </p>
</div>

app/views/clients/_client_index.html.erb
<div class="client row">
  <div class="col-xs-6 col-sm-3">
    <p class="name"><%= client_name(client) %></p>
  </div>
  <div class="col-xs-6 col-sm-3">
    <p><%= client_email(client) %></p>
  </div>
  <div class="col-xs-6 col-sm-3">
    <p><%= client_phone(client) %> </p>
  </div>
  <div class="col-sm-3">
    <div class="hidden-xs">
      <p><%= appointment_count(client) %></p>
      <p><%= client_value(client) %></p>
    </div>
    <p><%= link_to "New Appointment", new_client_appointment_path(client), class: "btn btn-primary" %></p>
  </div>
</div>

app/views/clients/_form.html.erb
<div class="zoom2">
<%= render partial: 'layouts/errors', locals: { object: client } %>
<%= form_for client do |f| %>
  <p><%= f.label :name %> <%= f.text_field :name %></p>
  <p><%= f.label :phone_number %> <%= f.text_field :phone_number %></p>
  <p><%= f.label :email %> <%= f.text_field :email %></p>
  <p><%= f.submit %></p>
<% end %>

</div>

app/views/clients/edit.html.erb
<div class="zoom2">

<h1>Edit Client</h1>
<%= render partial: "form", locals: { client: @client } %>
<p>
  <%= link_to "Delete", @client, method: :delete, data: { confirm: "Are you sure you want to delete this client?" } %>
</p>
</div>

app/views/clients/index.html.erb
<div class="zoom">
<h1 >Clients <%= link_to "+ New", new_client_path %></h1>
<% if @clients.any? %>
  <div class="row">
  <div class="hidden-xs col-sm-9">
    <h3>Name</h3>
  </div>
  <div class="hidden-xs col-sm-3">
    <h3>Appointments</h3>
</div>
</div>
<% else %>
<p>No clients yet.</p>
<% end %>
<%= render partial: "client_index", collection: @clients, as: :client %>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>
<%= render partial: 'form', locals: { client: @client } %>

app/views/clients/show.html.erb
<div class="zoom">

<h1>Client</h1>
<%= render @client %>
<h1>Appointments <%= link_to "+ New", new_client_appointment_path(@client) %></h1>
<%= render @appointments, template: "appointments/appointment" %>
</div>