config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :locations do
    resources :appointments, only: [:index, :show, :new]
  end
  resources :clients do
    resources :appointments, only: [:index, :show, :new]
  end
  get 'welcome/home'
  root 'welcome#home'

  get '/about', to: 'welcome#about'

  get '/locations/:id/client_list', to: 'locations#client_list', as: 'client_list'

end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">We've got what you need!</h2>
                <hr class="light">
                <p class="text-faded">A way to keep up with all of your clients and their favorite templates while tracking all the money you make from each client, in a way becoming your own booking team/staff.</p>
                <a href="users/sign_up" class="btn btn-default btn-xl">Get Started!</a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Download My Resume... It's Freeee!!!</h2>
            <a href="KalilW-Resume.docx" type="submit" class="btn btn-default btn-xl wow tada" download>DOWNLOAD NOW!!</a>
            <br>
            <a href="https://kalilw.herokuapp.com/">Veiw Online Resume</a>
        </div>
    </div>
</aside>

app/views/creatives/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="primary">
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
              <%= link_to fa_icon("phone"), root_path, class:'fa-4x bounceIn' %>
                <p>786-661-9324</p>
            </div>
            <a href="mailto:wkalil416@gmail.com">
            <div class="col-lg-4 text-center">
              <%= link_to fa_icon("envelope"), "mailto:wkalil416@gmail.com", class:'fa-4x bounceIn' %>

                <p>wkalil416@gmail.com</p>
            </div>
          </a>
        </div>
    </div>
</section>

app/views/creatives/_header.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Track Your Clients, Appointment & More...</h1>
            <hr>
            <p>Start tracking your appointments with ease</p>
            <a href="users/sign_up" class="btn btn-primary btn-xl page-scroll">Sign Up Now</a>
        </div>
    </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Appointment Tracker</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <%# <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Services</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Portfolio</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li> %>
                <% if user_signed_in? %>
                <li><%= link_to "Clients", clients_path %></li>
                <li><%= link_to "templates", templates_path %></li>
                <li><%= link_to "Appointments", appointments_path %></li>
                <li class="right"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                <li class="right"><%= link_to "Sign in", new_user_session_path %></li>
                <%# <li class="right"><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) </li> %>
                <li class="right"><%= link_to "Sign up", new_user_registration_path %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/creatives/_portfolio.html.erb
<section class="no-padding" id="portfolio">
  <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2 class="section-heading">Some Of My Work</h2>
              <hr class="primary">
          </div>
      </div>
  </div>
    <div class="container-fluid">
        <div class="row ai">
            <div class="col-lg-4 col-sm-6">
                <a href="http://travelfever.herokuapp.com/" class="portfolio-box">
                    <%= image_tag "Travelfever.png", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                              Project
                            </div>
                            <div class="project-name">
                                Travelfever
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="https://www.govlia.com/" class="portfolio-box">
                  <%= image_tag "Govlia.png", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                              https://www.govlia.com/
                            </div>
                            <div class="project-name">
                                Govlia
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="https://offeroff.herokuapp.com/" class="portfolio-box">
                    <%= image_tag "Offerme.png", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                              Project
                            </div>
                            <div class="project-name">
                              Offerme
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="https://photoscape.herokuapp.com/" class="portfolio-box">
                    <%= image_tag "fotoscape.png", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Project
                            </div>
                            <div class="project-name">
                              Photoscape
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="https://kalilw.herokuapp.com/" class="portfolio-box">
                    <%= image_tag "Portfolio.png", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                              Project
                            </div>
                            <div class="project-name">
                              Portfolio
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="https://github.com/kalil1" class="portfolio-box">
                    <%= image_tag "github.png", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                              GitHub
                            </div>
                            <div class="project-name">
                              Kalil1
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                  <%= link_to fa_icon("gem"), root_path, class:'fa-4x bounceIn' %>
                    <h3>Sturdy</h3>
                    <p class="text-muted">This project is updated regularly so it won't break.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                  <%= link_to fa_icon("paper-plane"), root_path, class:'fa-4x bounceIn' %>
                    <h3>Versatile</h3>
                    <p class="text-muted">You can use this to manage just about any service you provide</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                  <%= link_to fa_icon("newspaper-o"), root_path, class:'fa-4x bounceIn' %>
                  <h3>Up to Date</h3>
                    <p class="text-muted">We update dependencies to keep things fresh.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                  <%= link_to fa_icon("heart"), root_path, class:'fa-4x bounceIn' %>
                    <h3>Made with Love</h3>
                    <p class="text-muted">You have to make your websites with love these days!</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/creatives/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'services' %>
<%= render 'portfolio' %>
<%= render 'call_to_action' %>
<%= render 'contact' %>