config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :locations do
    resources :appointments, only: [:index, :show, :new]
  end
  resources :clients do
    resources :appointments, only: [:index, :show, :new]
  end
  get 'welcome/home'
  root 'welcome#home'

  get '/about', to: 'welcome#about'

  get '/locations/:id/client_list', to: 'locations#client_list', as: 'client_list'

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :clients, through: :appointments
  
  def client_count 
    clients.count
  end
  
  def appointment_count 
    appointments.count
  end
  
  def value
    appointments.collect { |a| a.price }.compact.inject(0, :+)
  end
  
  validates :nickname, presence: true
end

app/views/locations/_form.html.erb
<div class="zoom2">
<%= render partial: "layouts/errors", locals: { object: location } %>
<%= form_for location do |f| %>
  <p>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :street_address %>
    <%= f.text_field :street_address %>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </p>
  <p>
    <%= f.label :business_name %>
    <%= f.text_field :business_name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

</div>

app/views/locations/client_list.html.erb
<h1>Client List</h1>
<h3>Location</h3>
<h5><%= link_to @location.nickname, location_path(@location) %></h5>
<p><%= show_address(@location) %></p>

<h3>Clients</h3>
<ul>
  <% @clients.each do |client| %> 
    <li><%= link_to client.name, client_path(client) %></li>
  <% end %>
</ul>

app/views/locations/index.html.erb
<div class="zoom">
<h1>Locations <%= link_to "+ New", new_location_path %></h1>
<% if @locations.any? %>
<div class="row">
  <div class="col-sm-5 hidden-xs">
    <h3>Nickname</h3>
  </div>
  <div class="col-sm-4 hidden-xs">
    <h3>Address</h3>
  </div>
  <div class="col-sm-3 hidden-xs">
    <h3>Appointments</h3>
  </div>
</div>
<% else %>
<p>No locations yet.</p>
<% end %>
<div class="locations">
  <%= render partial: "location_index", collection: @locations, as: :location %>
</div>

</div>